#!/usr/bin/expect 

# timeout script after 20 seconds
set timeout 20 

set hostname modem
set password %PASSWORD%

# start the telnet client
spawn telnet $hostname 

# Wait for "Password:"
expect "Password: " 
send "$password\n"

# Get line status
expect "> "
send "wan adsl status\n"

# Get uptime
expect "> "
send "wan adsl uptime\n"

# Get far linedata
expect "> "
send "wan adsl linedata far\n"

# Get near linedata
expect "> "
send "wan adsl linedata near\n"

# get rates
expect "> "
send "wan adsl chandata\n"

# Exit modem interface
expect "> "
send "exit\n"
