#!/usr/bin/expect 

# timeout script after 20 seconds
set timeout 20 

set hostname modem
set password %PASSWORD%

# start the telnet client
spawn telnet $hostname 

# Wait for "Password:"
expect "Password: " 
send "$password\n"

expect "> "
send "wan adsl reset\n"

# Exit modem interface
expect "> "
send "exit\n"
